module.exports = {
  /* UNKNOWN */
  ERR_ACTION_UNKOWN: 'ERR_ACTION_UNKOWN',
  /* REGISTRATION */
  REGISTER_USER: 'REGISTER_USER',
  /* MESSAGES */
  MESSAGE_DELIVERED: 'MESSAGE_DELIVERED',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  /* TYPING INDICATORS */
  TOGGLE_TYPING: 'TOGGLE_TYPING',
  USER_TYPING: 'USER_TYPING',
}